/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutListResponseDataItemAttributes } from './AboutListResponseDataItemAttributes';
import {
  AboutListResponseDataItemAttributesFromJSON,
  AboutListResponseDataItemAttributesFromJSONTyped,
  AboutListResponseDataItemAttributesToJSON,
} from './AboutListResponseDataItemAttributes';

/**
 *
 * @export
 * @interface AboutListResponseDataItem
 */
export interface AboutListResponseDataItem {
  /**
   *
   * @type {number}
   * @memberof AboutListResponseDataItem
   */
  id?: number;
  /**
   *
   * @type {AboutListResponseDataItemAttributes}
   * @memberof AboutListResponseDataItem
   */
  attributes?: AboutListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the AboutListResponseDataItem interface.
 */
export function instanceOfAboutListResponseDataItem(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutListResponseDataItemFromJSON(json: any): AboutListResponseDataItem {
  return AboutListResponseDataItemFromJSONTyped(json, false);
}

export function AboutListResponseDataItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutListResponseDataItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : AboutListResponseDataItemAttributesFromJSON(json['attributes']),
  };
}

export function AboutListResponseDataItemToJSON(value?: AboutListResponseDataItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: AboutListResponseDataItemAttributesToJSON(value.attributes),
  };
}
