/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AboutImageDataAttributesRelatedDataInner
 */
export interface AboutImageDataAttributesRelatedDataInner {
  /**
   *
   * @type {number}
   * @memberof AboutImageDataAttributesRelatedDataInner
   */
  id?: number;
  /**
   *
   * @type {object}
   * @memberof AboutImageDataAttributesRelatedDataInner
   */
  attributes?: object;
}

/**
 * Check if a given object implements the AboutImageDataAttributesRelatedDataInner interface.
 */
export function instanceOfAboutImageDataAttributesRelatedDataInner(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutImageDataAttributesRelatedDataInnerFromJSON(
  json: any
): AboutImageDataAttributesRelatedDataInner {
  return AboutImageDataAttributesRelatedDataInnerFromJSONTyped(json, false);
}

export function AboutImageDataAttributesRelatedDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutImageDataAttributesRelatedDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes') ? undefined : json['attributes'],
  };
}

export function AboutImageDataAttributesRelatedDataInnerToJSON(
  value?: AboutImageDataAttributesRelatedDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: value.attributes,
  };
}
