/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { About } from './About';
import { AboutFromJSON, AboutFromJSONTyped, AboutToJSON } from './About';

/**
 *
 * @export
 * @interface AboutResponseDataObjectLocalized
 */
export interface AboutResponseDataObjectLocalized {
  /**
   *
   * @type {number}
   * @memberof AboutResponseDataObjectLocalized
   */
  id?: number;
  /**
   *
   * @type {About}
   * @memberof AboutResponseDataObjectLocalized
   */
  attributes?: About;
}

/**
 * Check if a given object implements the AboutResponseDataObjectLocalized interface.
 */
export function instanceOfAboutResponseDataObjectLocalized(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutResponseDataObjectLocalizedFromJSON(
  json: any
): AboutResponseDataObjectLocalized {
  return AboutResponseDataObjectLocalizedFromJSONTyped(json, false);
}

export function AboutResponseDataObjectLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutResponseDataObjectLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes') ? undefined : AboutFromJSON(json['attributes']),
  };
}

export function AboutResponseDataObjectLocalizedToJSON(
  value?: AboutResponseDataObjectLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: AboutToJSON(value.attributes),
  };
}
