/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImageDataAttributesFolder } from './AboutLocalizationResponseImageDataAttributesFolder';
import {
  AboutLocalizationResponseImageDataAttributesFolderFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolder';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { AboutLocalizationResponseImageDataAttributesRelated } from './AboutLocalizationResponseImageDataAttributesRelated';
import {
  AboutLocalizationResponseImageDataAttributesRelatedFromJSON,
  AboutLocalizationResponseImageDataAttributesRelatedFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesRelatedToJSON,
} from './AboutLocalizationResponseImageDataAttributesRelated';

/**
 *
 * @export
 * @interface AboutLocalizationResponseImageDataAttributes
 */
export interface AboutLocalizationResponseImageDataAttributes {
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  alternativeText?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  caption?: string;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  width?: number;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  height?: number;
  /**
   *
   * @type {any}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  formats?: any | null;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  hash?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  ext?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  mime?: string;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  size?: number;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  previewUrl?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  provider?: string;
  /**
   *
   * @type {any}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  providerMetadata?: any | null;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesRelated}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  related?: AboutLocalizationResponseImageDataAttributesRelated;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolder}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  folder?: AboutLocalizationResponseImageDataAttributesFolder;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  folderPath?: string;
  /**
   *
   * @type {Date}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof AboutLocalizationResponseImageDataAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the AboutLocalizationResponseImageDataAttributes interface.
 */
export function instanceOfAboutLocalizationResponseImageDataAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutLocalizationResponseImageDataAttributesFromJSON(
  json: any
): AboutLocalizationResponseImageDataAttributes {
  return AboutLocalizationResponseImageDataAttributesFromJSONTyped(json, false);
}

export function AboutLocalizationResponseImageDataAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutLocalizationResponseImageDataAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    alternativeText: !exists(json, 'alternativeText') ? undefined : json['alternativeText'],
    caption: !exists(json, 'caption') ? undefined : json['caption'],
    width: !exists(json, 'width') ? undefined : json['width'],
    height: !exists(json, 'height') ? undefined : json['height'],
    formats: !exists(json, 'formats') ? undefined : json['formats'],
    hash: !exists(json, 'hash') ? undefined : json['hash'],
    ext: !exists(json, 'ext') ? undefined : json['ext'],
    mime: !exists(json, 'mime') ? undefined : json['mime'],
    size: !exists(json, 'size') ? undefined : json['size'],
    url: !exists(json, 'url') ? undefined : json['url'],
    previewUrl: !exists(json, 'previewUrl') ? undefined : json['previewUrl'],
    provider: !exists(json, 'provider') ? undefined : json['provider'],
    providerMetadata: !exists(json, 'provider_metadata') ? undefined : json['provider_metadata'],
    related: !exists(json, 'related')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesRelatedFromJSON(json['related']),
    folder: !exists(json, 'folder')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderFromJSON(json['folder']),
    folderPath: !exists(json, 'folderPath') ? undefined : json['folderPath'],
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
  };
}

export function AboutLocalizationResponseImageDataAttributesToJSON(
  value?: AboutLocalizationResponseImageDataAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    alternativeText: value.alternativeText,
    caption: value.caption,
    width: value.width,
    height: value.height,
    formats: value.formats,
    hash: value.hash,
    ext: value.ext,
    mime: value.mime,
    size: value.size,
    url: value.url,
    previewUrl: value.previewUrl,
    provider: value.provider,
    provider_metadata: value.providerMetadata,
    related: AboutLocalizationResponseImageDataAttributesRelatedToJSON(value.related),
    folder: AboutLocalizationResponseImageDataAttributesFolderToJSON(value.folder),
    folderPath: value.folderPath,
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.createdBy
    ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
  };
}
