/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutResponseDataObject } from './AboutResponseDataObject';
import {
  AboutResponseDataObjectFromJSON,
  AboutResponseDataObjectFromJSONTyped,
  AboutResponseDataObjectToJSON,
} from './AboutResponseDataObject';

/**
 *
 * @export
 * @interface AboutResponse
 */
export interface AboutResponse {
  /**
   *
   * @type {AboutResponseDataObject}
   * @memberof AboutResponse
   */
  data?: AboutResponseDataObject;
  /**
   *
   * @type {object}
   * @memberof AboutResponse
   */
  meta?: object;
}

/**
 * Check if a given object implements the AboutResponse interface.
 */
export function instanceOfAboutResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutResponseFromJSON(json: any): AboutResponse {
  return AboutResponseFromJSONTyped(json, false);
}

export function AboutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AboutResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : AboutResponseDataObjectFromJSON(json['data']),
    meta: !exists(json, 'meta') ? undefined : json['meta'],
  };
}

export function AboutResponseToJSON(value?: AboutResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: AboutResponseDataObjectToJSON(value.data),
    meta: value.meta,
  };
}
