/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImage } from './AboutLocalizationResponseImage';
import {
  AboutLocalizationResponseImageFromJSON,
  AboutLocalizationResponseImageFromJSONTyped,
  AboutLocalizationResponseImageToJSON,
} from './AboutLocalizationResponseImage';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { AboutResponseDataObjectAttributesLocalizations } from './AboutResponseDataObjectAttributesLocalizations';
import {
  AboutResponseDataObjectAttributesLocalizationsFromJSON,
  AboutResponseDataObjectAttributesLocalizationsFromJSONTyped,
  AboutResponseDataObjectAttributesLocalizationsToJSON,
} from './AboutResponseDataObjectAttributesLocalizations';
import type { ContactLinkComponent } from './ContactLinkComponent';
import {
  ContactLinkComponentFromJSON,
  ContactLinkComponentFromJSONTyped,
  ContactLinkComponentToJSON,
} from './ContactLinkComponent';

/**
 *
 * @export
 * @interface AboutResponseDataObjectAttributes
 */
export interface AboutResponseDataObjectAttributes {
  /**
   *
   * @type {string}
   * @memberof AboutResponseDataObjectAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof AboutResponseDataObjectAttributes
   */
  content?: string;
  /**
   *
   * @type {AboutLocalizationResponseImage}
   * @memberof AboutResponseDataObjectAttributes
   */
  image?: AboutLocalizationResponseImage;
  /**
   *
   * @type {Array<ContactLinkComponent>}
   * @memberof AboutResponseDataObjectAttributes
   */
  links?: Array<ContactLinkComponent>;
  /**
   *
   * @type {Date}
   * @memberof AboutResponseDataObjectAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof AboutResponseDataObjectAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy}
   * @memberof AboutResponseDataObjectAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof AboutResponseDataObjectAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutResponseDataObjectAttributesLocalizations}
   * @memberof AboutResponseDataObjectAttributes
   */
  localizations?: AboutResponseDataObjectAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof AboutResponseDataObjectAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the AboutResponseDataObjectAttributes interface.
 */
export function instanceOfAboutResponseDataObjectAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutResponseDataObjectAttributesFromJSON(
  json: any
): AboutResponseDataObjectAttributes {
  return AboutResponseDataObjectAttributesFromJSONTyped(json, false);
}

export function AboutResponseDataObjectAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutResponseDataObjectAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    content: !exists(json, 'content') ? undefined : json['content'],
    image: !exists(json, 'image')
      ? undefined
      : AboutLocalizationResponseImageFromJSON(json['image']),
    links: !exists(json, 'links')
      ? undefined
      : (json['links'] as Array<any>).map(ContactLinkComponentFromJSON),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
    localizations: !exists(json, 'localizations')
      ? undefined
      : AboutResponseDataObjectAttributesLocalizationsFromJSON(json['localizations']),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function AboutResponseDataObjectAttributesToJSON(
  value?: AboutResponseDataObjectAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    content: value.content,
    image: AboutLocalizationResponseImageToJSON(value.image),
    links:
      value.links === undefined
        ? undefined
        : (value.links as Array<any>).map(ContactLinkComponentToJSON),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
        value.createdBy
      ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
    localizations: AboutResponseDataObjectAttributesLocalizationsToJSON(value.localizations),
    locale: value.locale,
  };
}
