/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { AboutLocalizationResponseImageDataAttributesRelated } from './AboutLocalizationResponseImageDataAttributesRelated';
import {
  AboutLocalizationResponseImageDataAttributesRelatedFromJSON,
  AboutLocalizationResponseImageDataAttributesRelatedFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesRelatedToJSON,
} from './AboutLocalizationResponseImageDataAttributesRelated';

/**
 *
 * @export
 * @interface AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
 */
export interface AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  alternativeText?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  caption?: string;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  width?: number;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  height?: number;
  /**
   *
   * @type {any}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  formats?: any | null;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  hash?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  ext?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  mime?: string;
  /**
   *
   * @type {number}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  size?: number;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  previewUrl?: string;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  provider?: string;
  /**
   *
   * @type {any}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  providerMetadata?: any | null;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesRelated}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  related?: AboutLocalizationResponseImageDataAttributesRelated;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  folder?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {string}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  folderPath?: string;
  /**
   *
   * @type {Date}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes interface.
 */
export function instanceOfAboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesFromJSON(
  json: any
): AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes {
  return AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    alternativeText: !exists(json, 'alternativeText') ? undefined : json['alternativeText'],
    caption: !exists(json, 'caption') ? undefined : json['caption'],
    width: !exists(json, 'width') ? undefined : json['width'],
    height: !exists(json, 'height') ? undefined : json['height'],
    formats: !exists(json, 'formats') ? undefined : json['formats'],
    hash: !exists(json, 'hash') ? undefined : json['hash'],
    ext: !exists(json, 'ext') ? undefined : json['ext'],
    mime: !exists(json, 'mime') ? undefined : json['mime'],
    size: !exists(json, 'size') ? undefined : json['size'],
    url: !exists(json, 'url') ? undefined : json['url'],
    previewUrl: !exists(json, 'previewUrl') ? undefined : json['previewUrl'],
    provider: !exists(json, 'provider') ? undefined : json['provider'],
    providerMetadata: !exists(json, 'provider_metadata') ? undefined : json['provider_metadata'],
    related: !exists(json, 'related')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesRelatedFromJSON(json['related']),
    folder: !exists(json, 'folder')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['folder']
        ),
    folderPath: !exists(json, 'folderPath') ? undefined : json['folderPath'],
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
  };
}

export function AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesToJSON(
  value?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    alternativeText: value.alternativeText,
    caption: value.caption,
    width: value.width,
    height: value.height,
    formats: value.formats,
    hash: value.hash,
    ext: value.ext,
    mime: value.mime,
    size: value.size,
    url: value.url,
    previewUrl: value.previewUrl,
    provider: value.provider,
    provider_metadata: value.providerMetadata,
    related: AboutLocalizationResponseImageDataAttributesRelatedToJSON(value.related),
    folder: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.folder
    ),
    folderPath: value.folderPath,
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
        value.createdBy
      ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
  };
}
