/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AboutLocalizationResponseLocalizations
 */
export interface AboutLocalizationResponseLocalizations {
  /**
   *
   * @type {Array<any>}
   * @memberof AboutLocalizationResponseLocalizations
   */
  data?: Array<any>;
}

/**
 * Check if a given object implements the AboutLocalizationResponseLocalizations interface.
 */
export function instanceOfAboutLocalizationResponseLocalizations(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutLocalizationResponseLocalizationsFromJSON(
  json: any
): AboutLocalizationResponseLocalizations {
  return AboutLocalizationResponseLocalizationsFromJSONTyped(json, false);
}

export function AboutLocalizationResponseLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutLocalizationResponseLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : json['data'],
  };
}

export function AboutLocalizationResponseLocalizationsToJSON(
  value?: AboutLocalizationResponseLocalizations | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data,
  };
}
