/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutImageDataAttributesRelatedDataInner } from './AboutImageDataAttributesRelatedDataInner';
import {
  AboutImageDataAttributesRelatedDataInnerFromJSON,
  AboutImageDataAttributesRelatedDataInnerFromJSONTyped,
  AboutImageDataAttributesRelatedDataInnerToJSON,
} from './AboutImageDataAttributesRelatedDataInner';

/**
 *
 * @export
 * @interface AboutImageDataAttributesFolderDataAttributesParent
 */
export interface AboutImageDataAttributesFolderDataAttributesParent {
  /**
   *
   * @type {AboutImageDataAttributesRelatedDataInner}
   * @memberof AboutImageDataAttributesFolderDataAttributesParent
   */
  data?: AboutImageDataAttributesRelatedDataInner;
}

/**
 * Check if a given object implements the AboutImageDataAttributesFolderDataAttributesParent interface.
 */
export function instanceOfAboutImageDataAttributesFolderDataAttributesParent(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutImageDataAttributesFolderDataAttributesParentFromJSON(
  json: any
): AboutImageDataAttributesFolderDataAttributesParent {
  return AboutImageDataAttributesFolderDataAttributesParentFromJSONTyped(json, false);
}

export function AboutImageDataAttributesFolderDataAttributesParentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutImageDataAttributesFolderDataAttributesParent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : AboutImageDataAttributesRelatedDataInnerFromJSON(json['data']),
  };
}

export function AboutImageDataAttributesFolderDataAttributesParentToJSON(
  value?: AboutImageDataAttributesFolderDataAttributesParent | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: AboutImageDataAttributesRelatedDataInnerToJSON(value.data),
  };
}
