/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutListResponseDataItem } from './AboutListResponseDataItem';
import {
  AboutListResponseDataItemFromJSON,
  AboutListResponseDataItemFromJSONTyped,
  AboutListResponseDataItemToJSON,
} from './AboutListResponseDataItem';
import type { AboutListResponseMeta } from './AboutListResponseMeta';
import {
  AboutListResponseMetaFromJSON,
  AboutListResponseMetaFromJSONTyped,
  AboutListResponseMetaToJSON,
} from './AboutListResponseMeta';

/**
 *
 * @export
 * @interface AboutListResponse
 */
export interface AboutListResponse {
  /**
   *
   * @type {Array<AboutListResponseDataItem>}
   * @memberof AboutListResponse
   */
  data?: Array<AboutListResponseDataItem>;
  /**
   *
   * @type {AboutListResponseMeta}
   * @memberof AboutListResponse
   */
  meta?: AboutListResponseMeta;
}

/**
 * Check if a given object implements the AboutListResponse interface.
 */
export function instanceOfAboutListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AboutListResponseFromJSON(json: any): AboutListResponse {
  return AboutListResponseFromJSONTyped(json, false);
}

export function AboutListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AboutListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(AboutListResponseDataItemFromJSON),
    meta: !exists(json, 'meta') ? undefined : AboutListResponseMetaFromJSON(json['meta']),
  };
}

export function AboutListResponseToJSON(value?: AboutListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(AboutListResponseDataItemToJSON),
    meta: AboutListResponseMetaToJSON(value.meta),
  };
}
