/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistListResponseDataItemLocalized } from './ArtistListResponseDataItemLocalized';
import {
  ArtistListResponseDataItemLocalizedFromJSON,
  ArtistListResponseDataItemLocalizedFromJSONTyped,
  ArtistListResponseDataItemLocalizedToJSON,
} from './ArtistListResponseDataItemLocalized';

/**
 *
 * @export
 * @interface ArtistListResponseDataItemAttributesLocalizations
 */
export interface ArtistListResponseDataItemAttributesLocalizations {
  /**
   *
   * @type {Array<ArtistListResponseDataItemLocalized>}
   * @memberof ArtistListResponseDataItemAttributesLocalizations
   */
  data?: Array<ArtistListResponseDataItemLocalized>;
}

/**
 * Check if a given object implements the ArtistListResponseDataItemAttributesLocalizations interface.
 */
export function instanceOfArtistListResponseDataItemAttributesLocalizations(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistListResponseDataItemAttributesLocalizationsFromJSON(
  json: any
): ArtistListResponseDataItemAttributesLocalizations {
  return ArtistListResponseDataItemAttributesLocalizationsFromJSONTyped(json, false);
}

export function ArtistListResponseDataItemAttributesLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistListResponseDataItemAttributesLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(ArtistListResponseDataItemLocalizedFromJSON),
  };
}

export function ArtistListResponseDataItemAttributesLocalizationsToJSON(
  value?: ArtistListResponseDataItemAttributesLocalizations | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(ArtistListResponseDataItemLocalizedToJSON),
  };
}
