/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistResponseDataObjectAttributes } from './ArtistResponseDataObjectAttributes';
import {
  ArtistResponseDataObjectAttributesFromJSON,
  ArtistResponseDataObjectAttributesFromJSONTyped,
  ArtistResponseDataObjectAttributesToJSON,
} from './ArtistResponseDataObjectAttributes';

/**
 *
 * @export
 * @interface ArtistResponseDataObject
 */
export interface ArtistResponseDataObject {
  /**
   *
   * @type {number}
   * @memberof ArtistResponseDataObject
   */
  id?: number;
  /**
   *
   * @type {ArtistResponseDataObjectAttributes}
   * @memberof ArtistResponseDataObject
   */
  attributes?: ArtistResponseDataObjectAttributes;
}

/**
 * Check if a given object implements the ArtistResponseDataObject interface.
 */
export function instanceOfArtistResponseDataObject(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistResponseDataObjectFromJSON(json: any): ArtistResponseDataObject {
  return ArtistResponseDataObjectFromJSONTyped(json, false);
}

export function ArtistResponseDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistResponseDataObject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtistResponseDataObjectAttributesFromJSON(json['attributes']),
  };
}

export function ArtistResponseDataObjectToJSON(value?: ArtistResponseDataObject | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: ArtistResponseDataObjectAttributesToJSON(value.attributes),
  };
}
