/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolder } from './ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolder';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolder';

/**
 *
 * @export
 * @interface ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
 */
export interface ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  alternativeText?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  caption?: string;
  /**
   *
   * @type {number}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  width?: number;
  /**
   *
   * @type {number}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  height?: number;
  /**
   *
   * @type {any}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  formats?: any | null;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  hash?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  ext?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  mime?: string;
  /**
   *
   * @type {number}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  size?: number;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  previewUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  provider?: string;
  /**
   *
   * @type {any}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  providerMetadata?: any | null;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  related?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolder}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  folder?: ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolder;
  /**
   *
   * @type {string}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  folderPath?: string;
  /**
   *
   * @type {Date}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  createdBy?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes
   */
  updatedBy?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole;
}

/**
 * Check if a given object implements the ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes interface.
 */
export function instanceOfArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFromJSON(
  json: any
): ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes {
  return ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    alternativeText: !exists(json, 'alternativeText') ? undefined : json['alternativeText'],
    caption: !exists(json, 'caption') ? undefined : json['caption'],
    width: !exists(json, 'width') ? undefined : json['width'],
    height: !exists(json, 'height') ? undefined : json['height'],
    formats: !exists(json, 'formats') ? undefined : json['formats'],
    hash: !exists(json, 'hash') ? undefined : json['hash'],
    ext: !exists(json, 'ext') ? undefined : json['ext'],
    mime: !exists(json, 'mime') ? undefined : json['mime'],
    size: !exists(json, 'size') ? undefined : json['size'],
    url: !exists(json, 'url') ? undefined : json['url'],
    previewUrl: !exists(json, 'previewUrl') ? undefined : json['previewUrl'],
    provider: !exists(json, 'provider') ? undefined : json['provider'],
    providerMetadata: !exists(json, 'provider_metadata') ? undefined : json['provider_metadata'],
    related: !exists(json, 'related')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSON(
          json['related']
        ),
    folder: !exists(json, 'folder')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderFromJSON(
          json['folder']
        ),
    folderPath: !exists(json, 'folderPath') ? undefined : json['folderPath'],
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleFromJSON(
          json['updatedBy']
        ),
  };
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesToJSON(
  value?: ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    alternativeText: value.alternativeText,
    caption: value.caption,
    width: value.width,
    height: value.height,
    formats: value.formats,
    hash: value.hash,
    ext: value.ext,
    mime: value.mime,
    size: value.size,
    url: value.url,
    previewUrl: value.previewUrl,
    provider: value.provider,
    provider_metadata: value.providerMetadata,
    related:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksToJSON(
        value.related
      ),
    folder:
      ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderToJSON(
        value.folder
      ),
    folderPath: value.folderPath,
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleToJSON(
        value.createdBy
      ),
    updatedBy:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRoleToJSON(
        value.updatedBy
      ),
  };
}
