/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributes } from './ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributes';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributesFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributesFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributesToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributes';

/**
 *
 * @export
 * @interface ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData
 */
export interface ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData {
  /**
   *
   * @type {number}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData
   */
  id?: number;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributes}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData
   */
  attributes?: ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributes;
}

/**
 * Check if a given object implements the ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData interface.
 */
export function instanceOfArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataFromJSON(
  json: any
): ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData {
  return ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataFromJSONTyped(
    json,
    false
  );
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributesFromJSON(
          json['attributes']
        ),
  };
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataToJSON(
  value?: ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      ArtistLocalizationResponseArtworksDataInnerAttributesMediaDataInnerAttributesFolderDataAttributesToJSON(
        value.attributes
      ),
  };
}
