/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner
 */
export interface ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner {
  /**
   *
   * @type {number}
   * @memberof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner
   */
  handle?: string;
  /**
   *
   * @type {string}
   * @memberof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner
   */
  platform?: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerPlatformEnum;
  /**
   *
   * @type {string}
   * @memberof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner
   */
  url?: string;
}

/**
 * @export
 */
export const ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerPlatformEnum = {
  Generic: 'generic',
  Email: 'email',
  Website: 'website',
  Facebook: 'facebook',
  Youtube: 'youtube',
  Instagram: 'instagram',
  Tiktok: 'tiktok',
  Snapchat: 'snapchat',
  Twitter: 'twitter',
  Reddit: 'reddit',
  Discord: 'discord',
  Twitch: 'twitch',
  Github: 'github',
  Paypal: 'paypal',
} as const;
export type ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerPlatformEnum =
  (typeof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerPlatformEnum)[keyof typeof ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerPlatformEnum];

/**
 * Check if a given object implements the ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner interface.
 */
export function instanceOfArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerFromJSON(
  json: any
): ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner {
  return ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerFromJSONTyped(
    json,
    false
  );
}

export function ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    handle: !exists(json, 'handle') ? undefined : json['handle'],
    platform: !exists(json, 'platform') ? undefined : json['platform'],
    url: !exists(json, 'url') ? undefined : json['url'],
  };
}

export function ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInnerToJSON(
  value?: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesContactInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    handle: value.handle,
    platform: value.platform,
    url: value.url,
  };
}
