/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistArtworksDataInnerAttributesMediaDataInner } from './ArtistArtworksDataInnerAttributesMediaDataInner';
import {
  ArtistArtworksDataInnerAttributesMediaDataInnerFromJSON,
  ArtistArtworksDataInnerAttributesMediaDataInnerFromJSONTyped,
  ArtistArtworksDataInnerAttributesMediaDataInnerToJSON,
} from './ArtistArtworksDataInnerAttributesMediaDataInner';

/**
 *
 * @export
 * @interface ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover
 */
export interface ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover {
  /**
   *
   * @type {ArtistArtworksDataInnerAttributesMediaDataInner}
   * @memberof ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover
   */
  data?: ArtistArtworksDataInnerAttributesMediaDataInner;
}

/**
 * Check if a given object implements the ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover interface.
 */
export function instanceOfArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSON(
  json: any
): ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover {
  return ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSONTyped(
    json,
    false
  );
}

export function ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : ArtistArtworksDataInnerAttributesMediaDataInnerFromJSON(json['data']),
  };
}

export function ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverToJSON(
  value?: ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ArtistArtworksDataInnerAttributesMediaDataInnerToJSON(value.data),
  };
}
