/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistArtworksDataInnerAttributesArtistsDataInner } from './ArtistArtworksDataInnerAttributesArtistsDataInner';
import {
  ArtistArtworksDataInnerAttributesArtistsDataInnerFromJSON,
  ArtistArtworksDataInnerAttributesArtistsDataInnerFromJSONTyped,
  ArtistArtworksDataInnerAttributesArtistsDataInnerToJSON,
} from './ArtistArtworksDataInnerAttributesArtistsDataInner';

/**
 *
 * @export
 * @interface ArtistArtworksDataInnerAttributesArtists
 */
export interface ArtistArtworksDataInnerAttributesArtists {
  /**
   *
   * @type {Array<ArtistArtworksDataInnerAttributesArtistsDataInner>}
   * @memberof ArtistArtworksDataInnerAttributesArtists
   */
  data?: Array<ArtistArtworksDataInnerAttributesArtistsDataInner>;
}

/**
 * Check if a given object implements the ArtistArtworksDataInnerAttributesArtists interface.
 */
export function instanceOfArtistArtworksDataInnerAttributesArtists(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistArtworksDataInnerAttributesArtistsFromJSON(
  json: any
): ArtistArtworksDataInnerAttributesArtists {
  return ArtistArtworksDataInnerAttributesArtistsFromJSONTyped(json, false);
}

export function ArtistArtworksDataInnerAttributesArtistsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistArtworksDataInnerAttributesArtists {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(ArtistArtworksDataInnerAttributesArtistsDataInnerFromJSON),
  };
}

export function ArtistArtworksDataInnerAttributesArtistsToJSON(
  value?: ArtistArtworksDataInnerAttributesArtists | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(ArtistArtworksDataInnerAttributesArtistsDataInnerToJSON),
  };
}
