/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistListResponseDataItemLocalizedAttributes } from './ArtistListResponseDataItemLocalizedAttributes';
import {
  ArtistListResponseDataItemLocalizedAttributesFromJSON,
  ArtistListResponseDataItemLocalizedAttributesFromJSONTyped,
  ArtistListResponseDataItemLocalizedAttributesToJSON,
} from './ArtistListResponseDataItemLocalizedAttributes';

/**
 *
 * @export
 * @interface ArtistListResponseDataItemLocalized
 */
export interface ArtistListResponseDataItemLocalized {
  /**
   *
   * @type {number}
   * @memberof ArtistListResponseDataItemLocalized
   */
  id?: number;
  /**
   *
   * @type {ArtistListResponseDataItemLocalizedAttributes}
   * @memberof ArtistListResponseDataItemLocalized
   */
  attributes?: ArtistListResponseDataItemLocalizedAttributes;
}

/**
 * Check if a given object implements the ArtistListResponseDataItemLocalized interface.
 */
export function instanceOfArtistListResponseDataItemLocalized(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistListResponseDataItemLocalizedFromJSON(
  json: any
): ArtistListResponseDataItemLocalized {
  return ArtistListResponseDataItemLocalizedFromJSONTyped(json, false);
}

export function ArtistListResponseDataItemLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistListResponseDataItemLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtistListResponseDataItemLocalizedAttributesFromJSON(json['attributes']),
  };
}

export function ArtistListResponseDataItemLocalizedToJSON(
  value?: ArtistListResponseDataItemLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: ArtistListResponseDataItemLocalizedAttributesToJSON(value.attributes),
  };
}
