/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureData } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureData';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureData';

/**
 *
 * @export
 * @interface ArtistLocalizationResponseArtworksDataInnerAttributesMedia
 */
export interface ArtistLocalizationResponseArtworksDataInnerAttributesMedia {
  /**
   *
   * @type {Array<ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureData>}
   * @memberof ArtistLocalizationResponseArtworksDataInnerAttributesMedia
   */
  data?: Array<ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureData>;
}

/**
 * Check if a given object implements the ArtistLocalizationResponseArtworksDataInnerAttributesMedia interface.
 */
export function instanceOfArtistLocalizationResponseArtworksDataInnerAttributesMedia(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSON(
  json: any
): ArtistLocalizationResponseArtworksDataInnerAttributesMedia {
  return ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSONTyped(json, false);
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtistLocalizationResponseArtworksDataInnerAttributesMedia {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(
          ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataFromJSON
        ),
  };
}

export function ArtistLocalizationResponseArtworksDataInnerAttributesMediaToJSON(
  value?: ArtistLocalizationResponseArtworksDataInnerAttributesMedia | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataToJSON
          ),
  };
}
