/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistRequestData } from './ArtistRequestData';
import {
  ArtistRequestDataFromJSON,
  ArtistRequestDataFromJSONTyped,
  ArtistRequestDataToJSON,
} from './ArtistRequestData';

/**
 *
 * @export
 * @interface ArtistRequest
 */
export interface ArtistRequest {
  /**
   *
   * @type {ArtistRequestData}
   * @memberof ArtistRequest
   */
  data: ArtistRequestData;
}

/**
 * Check if a given object implements the ArtistRequest interface.
 */
export function instanceOfArtistRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;

  return isInstance;
}

export function ArtistRequestFromJSON(json: any): ArtistRequest {
  return ArtistRequestFromJSONTyped(json, false);
}

export function ArtistRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ArtistRequestDataFromJSON(json['data']),
  };
}

export function ArtistRequestToJSON(value?: ArtistRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ArtistRequestDataToJSON(value.data),
  };
}
