/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesMedia } from './ArtistLocalizationResponseArtworksDataInnerAttributesMedia';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesMedia';
import type { ArtworkListResponseDataItemAttributesLocalizations } from './ArtworkListResponseDataItemAttributesLocalizations';
import {
  ArtworkListResponseDataItemAttributesLocalizationsFromJSON,
  ArtworkListResponseDataItemAttributesLocalizationsFromJSONTyped,
  ArtworkListResponseDataItemAttributesLocalizationsToJSON,
} from './ArtworkListResponseDataItemAttributesLocalizations';
import type { ArtworkLocalizationResponseArtists } from './ArtworkLocalizationResponseArtists';
import {
  ArtworkLocalizationResponseArtistsFromJSON,
  ArtworkLocalizationResponseArtistsFromJSONTyped,
  ArtworkLocalizationResponseArtistsToJSON,
} from './ArtworkLocalizationResponseArtists';

/**
 *
 * @export
 * @interface ArtworkListResponseDataItemAttributes
 */
export interface ArtworkListResponseDataItemAttributes {
  /**
   *
   * @type {string}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  description?: string;
  /**
   *
   * @type {ArtworkLocalizationResponseArtists}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  artists?: ArtworkLocalizationResponseArtists;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesMedia}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  media?: ArtistLocalizationResponseArtworksDataInnerAttributesMedia;
  /**
   *
   * @type {Date}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  creationDate?: Date;
  /**
   *
   * @type {string}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  originalTitle?: string;
  /**
   *
   * @type {string}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  handle?: string;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  exhibitions?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworks;
  /**
   *
   * @type {Date}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  createdBy?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  updatedBy?: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {ArtworkListResponseDataItemAttributesLocalizations}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  localizations?: ArtworkListResponseDataItemAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof ArtworkListResponseDataItemAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the ArtworkListResponseDataItemAttributes interface.
 */
export function instanceOfArtworkListResponseDataItemAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkListResponseDataItemAttributesFromJSON(
  json: any
): ArtworkListResponseDataItemAttributes {
  return ArtworkListResponseDataItemAttributesFromJSONTyped(json, false);
}

export function ArtworkListResponseDataItemAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkListResponseDataItemAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    artists: !exists(json, 'artists')
      ? undefined
      : ArtworkLocalizationResponseArtistsFromJSON(json['artists']),
    media: !exists(json, 'media')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSON(json['media']),
    creationDate: !exists(json, 'creationDate') ? undefined : new Date(json['creationDate']),
    originalTitle: !exists(json, 'originalTitle') ? undefined : json['originalTitle'],
    handle: !exists(json, 'handle') ? undefined : json['handle'],
    exhibitions: !exists(json, 'exhibitions')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksFromJSON(
          json['exhibitions']
        ),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    publishedAt: !exists(json, 'publishedAt') ? undefined : new Date(json['publishedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
    localizations: !exists(json, 'localizations')
      ? undefined
      : ArtworkListResponseDataItemAttributesLocalizationsFromJSON(json['localizations']),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function ArtworkListResponseDataItemAttributesToJSON(
  value?: ArtworkListResponseDataItemAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    description: value.description,
    artists: ArtworkLocalizationResponseArtistsToJSON(value.artists),
    media: ArtistLocalizationResponseArtworksDataInnerAttributesMediaToJSON(value.media),
    creationDate:
      value.creationDate === undefined ? undefined : value.creationDate.toISOString().substr(0, 10),
    originalTitle: value.originalTitle,
    handle: value.handle,
    exhibitions:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesArtworksToJSON(
        value.exhibitions
      ),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt: value.publishedAt === undefined ? undefined : value.publishedAt.toISOString(),
    createdBy:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      ArtistLocalizationResponseArtworksDataInnerAttributesArtistsDataInnerAttributesPictureDataAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
    localizations: ArtworkListResponseDataItemAttributesLocalizationsToJSON(value.localizations),
    locale: value.locale,
  };
}
