/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutImageData } from './AboutImageData';
import {
  AboutImageDataFromJSON,
  AboutImageDataFromJSONTyped,
  AboutImageDataToJSON,
} from './AboutImageData';

/**
 *
 * @export
 * @interface ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia
 */
export interface ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia {
  /**
   *
   * @type {Array<AboutImageData>}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia
   */
  data?: Array<AboutImageData>;
}

/**
 * Check if a given object implements the ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia interface.
 */
export function instanceOfArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSON(
  json: any
): ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia {
  return ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSONTyped(
    json,
    false
  );
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(AboutImageDataFromJSON),
  };
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaToJSON(
  value?: ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined ? undefined : (value.data as Array<any>).map(AboutImageDataToJSON),
  };
}
