/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Artwork } from './Artwork';
import { ArtworkFromJSON, ArtworkFromJSONTyped, ArtworkToJSON } from './Artwork';

/**
 *
 * @export
 * @interface ArtworkLocalizations
 */
export interface ArtworkLocalizations {
  /**
   *
   * @type {Array<Artwork>}
   * @memberof ArtworkLocalizations
   */
  data?: Array<Artwork>;
}

/**
 * Check if a given object implements the ArtworkLocalizations interface.
 */
export function instanceOfArtworkLocalizations(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkLocalizationsFromJSON(json: any): ArtworkLocalizations {
  return ArtworkLocalizationsFromJSONTyped(json, false);
}

export function ArtworkLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(ArtworkFromJSON),
  };
}

export function ArtworkLocalizationsToJSON(value?: ArtworkLocalizations | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(ArtworkToJSON),
  };
}
