/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributes } from './ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributes';
import {
  ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSON,
  ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSONTyped,
  ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributesToJSON,
} from './ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributes';

/**
 *
 * @export
 * @interface ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner
 */
export interface ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner {
  /**
   *
   * @type {number}
   * @memberof ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner
   */
  id?: number;
  /**
   *
   * @type {ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributes}
   * @memberof ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner
   */
  attributes?: ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributes;
}

/**
 * Check if a given object implements the ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner interface.
 */
export function instanceOfArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerFromJSON(
  json: any
): ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner {
  return ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerFromJSONTyped(
    json,
    false
  );
}

export function ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSON(
          json['attributes']
        ),
  };
}

export function ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerToJSON(
  value?: ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      ArtworkLocalizationResponseArtistsDataInnerAttributesArtworksDataInnerAttributesToJSON(
        value.attributes
      ),
  };
}
