/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtworkLocalizationResponseArtistsDataInnerAttributes } from './ArtworkLocalizationResponseArtistsDataInnerAttributes';
import {
  ArtworkLocalizationResponseArtistsDataInnerAttributesFromJSON,
  ArtworkLocalizationResponseArtistsDataInnerAttributesFromJSONTyped,
  ArtworkLocalizationResponseArtistsDataInnerAttributesToJSON,
} from './ArtworkLocalizationResponseArtistsDataInnerAttributes';

/**
 *
 * @export
 * @interface ArtworkLocalizationResponseArtistsDataInner
 */
export interface ArtworkLocalizationResponseArtistsDataInner {
  /**
   *
   * @type {number}
   * @memberof ArtworkLocalizationResponseArtistsDataInner
   */
  id?: number;
  /**
   *
   * @type {ArtworkLocalizationResponseArtistsDataInnerAttributes}
   * @memberof ArtworkLocalizationResponseArtistsDataInner
   */
  attributes?: ArtworkLocalizationResponseArtistsDataInnerAttributes;
}

/**
 * Check if a given object implements the ArtworkLocalizationResponseArtistsDataInner interface.
 */
export function instanceOfArtworkLocalizationResponseArtistsDataInner(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkLocalizationResponseArtistsDataInnerFromJSON(
  json: any
): ArtworkLocalizationResponseArtistsDataInner {
  return ArtworkLocalizationResponseArtistsDataInnerFromJSONTyped(json, false);
}

export function ArtworkLocalizationResponseArtistsDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkLocalizationResponseArtistsDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtworkLocalizationResponseArtistsDataInnerAttributesFromJSON(json['attributes']),
  };
}

export function ArtworkLocalizationResponseArtistsDataInnerToJSON(
  value?: ArtworkLocalizationResponseArtistsDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: ArtworkLocalizationResponseArtistsDataInnerAttributesToJSON(value.attributes),
  };
}
