/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtworkLocalizationResponseArtistsDataInner } from './ArtworkLocalizationResponseArtistsDataInner';
import {
  ArtworkLocalizationResponseArtistsDataInnerFromJSON,
  ArtworkLocalizationResponseArtistsDataInnerFromJSONTyped,
  ArtworkLocalizationResponseArtistsDataInnerToJSON,
} from './ArtworkLocalizationResponseArtistsDataInner';

/**
 *
 * @export
 * @interface ArtworkLocalizationResponseArtists
 */
export interface ArtworkLocalizationResponseArtists {
  /**
   *
   * @type {Array<ArtworkLocalizationResponseArtistsDataInner>}
   * @memberof ArtworkLocalizationResponseArtists
   */
  data?: Array<ArtworkLocalizationResponseArtistsDataInner>;
}

/**
 * Check if a given object implements the ArtworkLocalizationResponseArtists interface.
 */
export function instanceOfArtworkLocalizationResponseArtists(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkLocalizationResponseArtistsFromJSON(
  json: any
): ArtworkLocalizationResponseArtists {
  return ArtworkLocalizationResponseArtistsFromJSONTyped(json, false);
}

export function ArtworkLocalizationResponseArtistsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkLocalizationResponseArtists {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(ArtworkLocalizationResponseArtistsDataInnerFromJSON),
  };
}

export function ArtworkLocalizationResponseArtistsToJSON(
  value?: ArtworkLocalizationResponseArtists | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(ArtworkLocalizationResponseArtistsDataInnerToJSON),
  };
}
