/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtworkResponseDataObject } from './ArtworkResponseDataObject';
import {
  ArtworkResponseDataObjectFromJSON,
  ArtworkResponseDataObjectFromJSONTyped,
  ArtworkResponseDataObjectToJSON,
} from './ArtworkResponseDataObject';

/**
 *
 * @export
 * @interface ArtworkResponse
 */
export interface ArtworkResponse {
  /**
   *
   * @type {ArtworkResponseDataObject}
   * @memberof ArtworkResponse
   */
  data?: ArtworkResponseDataObject;
  /**
   *
   * @type {object}
   * @memberof ArtworkResponse
   */
  meta?: object;
}

/**
 * Check if a given object implements the ArtworkResponse interface.
 */
export function instanceOfArtworkResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkResponseFromJSON(json: any): ArtworkResponse {
  return ArtworkResponseFromJSONTyped(json, false);
}

export function ArtworkResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data') ? undefined : ArtworkResponseDataObjectFromJSON(json['data']),
    meta: !exists(json, 'meta') ? undefined : json['meta'],
  };
}

export function ArtworkResponseToJSON(value?: ArtworkResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ArtworkResponseDataObjectToJSON(value.data),
    meta: value.meta,
  };
}
