/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutImageDataAttributesFolderDataAttributesParent } from './AboutImageDataAttributesFolderDataAttributesParent';
import {
  AboutImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutImageDataAttributesFolderDataAttributesParent';
import type { AboutImageDataAttributesRelated } from './AboutImageDataAttributesRelated';
import {
  AboutImageDataAttributesRelatedFromJSON,
  AboutImageDataAttributesRelatedFromJSONTyped,
  AboutImageDataAttributesRelatedToJSON,
} from './AboutImageDataAttributesRelated';
import type { ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations } from './ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations';
import {
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSON,
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSONTyped,
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsToJSON,
} from './ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations';
import type { ArtistArtworksDataInnerAttributesExhibitions } from './ArtistArtworksDataInnerAttributesExhibitions';
import {
  ArtistArtworksDataInnerAttributesExhibitionsFromJSON,
  ArtistArtworksDataInnerAttributesExhibitionsFromJSONTyped,
  ArtistArtworksDataInnerAttributesExhibitionsToJSON,
} from './ArtistArtworksDataInnerAttributesExhibitions';
import type { ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia } from './ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia';
import {
  ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSON,
  ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSONTyped,
  ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaToJSON,
} from './ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia';

/**
 *
 * @export
 * @interface ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
 */
export interface ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  description?: string;
  /**
   *
   * @type {AboutImageDataAttributesRelated}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  artists?: AboutImageDataAttributesRelated;
  /**
   *
   * @type {ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  media?: ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMedia;
  /**
   *
   * @type {Date}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  creationDate?: Date;
  /**
   *
   * @type {string}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  originalTitle?: string;
  /**
   *
   * @type {string}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  handle?: string;
  /**
   *
   * @type {ArtistArtworksDataInnerAttributesExhibitions}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  exhibitions?: ArtistArtworksDataInnerAttributesExhibitions;
  /**
   *
   * @type {Date}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {AboutImageDataAttributesFolderDataAttributesParent}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  createdBy?: AboutImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutImageDataAttributesFolderDataAttributesParent}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  updatedBy?: AboutImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  localizations?: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes interface.
 */
export function instanceOfArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSON(
  json: any
): ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes {
  return ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSONTyped(json, false);
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    artists: !exists(json, 'artists')
      ? undefined
      : AboutImageDataAttributesRelatedFromJSON(json['artists']),
    media: !exists(json, 'media')
      ? undefined
      : ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaFromJSON(json['media']),
    creationDate: !exists(json, 'creationDate') ? undefined : new Date(json['creationDate']),
    originalTitle: !exists(json, 'originalTitle') ? undefined : json['originalTitle'],
    handle: !exists(json, 'handle') ? undefined : json['handle'],
    exhibitions: !exists(json, 'exhibitions')
      ? undefined
      : ArtistArtworksDataInnerAttributesExhibitionsFromJSON(json['exhibitions']),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    publishedAt: !exists(json, 'publishedAt') ? undefined : new Date(json['publishedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutImageDataAttributesFolderDataAttributesParentFromJSON(json['createdBy']),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutImageDataAttributesFolderDataAttributesParentFromJSON(json['updatedBy']),
    localizations: !exists(json, 'localizations')
      ? undefined
      : ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSON(
          json['localizations']
        ),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesToJSON(
  value?: ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    description: value.description,
    artists: AboutImageDataAttributesRelatedToJSON(value.artists),
    media: ArtworkArtistsDataInnerAttributesArtworksDataInnerAttributesMediaToJSON(value.media),
    creationDate:
      value.creationDate === undefined ? undefined : value.creationDate.toISOString().substr(0, 10),
    originalTitle: value.originalTitle,
    handle: value.handle,
    exhibitions: ArtistArtworksDataInnerAttributesExhibitionsToJSON(value.exhibitions),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt: value.publishedAt === undefined ? undefined : value.publishedAt.toISOString(),
    createdBy: AboutImageDataAttributesFolderDataAttributesParentToJSON(value.createdBy),
    updatedBy: AboutImageDataAttributesFolderDataAttributesParentToJSON(value.updatedBy),
    localizations: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsToJSON(
      value.localizations
    ),
    locale: value.locale,
  };
}
