/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtworkResponseDataObjectAttributes } from './ArtworkResponseDataObjectAttributes';
import {
  ArtworkResponseDataObjectAttributesFromJSON,
  ArtworkResponseDataObjectAttributesFromJSONTyped,
  ArtworkResponseDataObjectAttributesToJSON,
} from './ArtworkResponseDataObjectAttributes';

/**
 *
 * @export
 * @interface ArtworkResponseDataObject
 */
export interface ArtworkResponseDataObject {
  /**
   *
   * @type {number}
   * @memberof ArtworkResponseDataObject
   */
  id?: number;
  /**
   *
   * @type {ArtworkResponseDataObjectAttributes}
   * @memberof ArtworkResponseDataObject
   */
  attributes?: ArtworkResponseDataObjectAttributes;
}

/**
 * Check if a given object implements the ArtworkResponseDataObject interface.
 */
export function instanceOfArtworkResponseDataObject(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ArtworkResponseDataObjectFromJSON(json: any): ArtworkResponseDataObject {
  return ArtworkResponseDataObjectFromJSONTyped(json, false);
}

export function ArtworkResponseDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ArtworkResponseDataObject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : ArtworkResponseDataObjectAttributesFromJSON(json['attributes']),
  };
}

export function ArtworkResponseDataObjectToJSON(value?: ArtworkResponseDataObject | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: ArtworkResponseDataObjectAttributesToJSON(value.attributes),
  };
}
