/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExhibitionRequestData } from './ExhibitionRequestData';
import {
  ExhibitionRequestDataFromJSON,
  ExhibitionRequestDataFromJSONTyped,
  ExhibitionRequestDataToJSON,
} from './ExhibitionRequestData';

/**
 *
 * @export
 * @interface ExhibitionRequest
 */
export interface ExhibitionRequest {
  /**
   *
   * @type {ExhibitionRequestData}
   * @memberof ExhibitionRequest
   */
  data: ExhibitionRequestData;
}

/**
 * Check if a given object implements the ExhibitionRequest interface.
 */
export function instanceOfExhibitionRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;

  return isInstance;
}

export function ExhibitionRequestFromJSON(json: any): ExhibitionRequest {
  return ExhibitionRequestFromJSONTyped(json, false);
}

export function ExhibitionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExhibitionRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: ExhibitionRequestDataFromJSON(json['data']),
  };
}

export function ExhibitionRequestToJSON(value?: ExhibitionRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: ExhibitionRequestDataToJSON(value.data),
  };
}
