/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { AboutLocalizationResponseImageDataAttributesRelated } from './AboutLocalizationResponseImageDataAttributesRelated';
import {
  AboutLocalizationResponseImageDataAttributesRelatedFromJSON,
  AboutLocalizationResponseImageDataAttributesRelatedFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesRelatedToJSON,
} from './AboutLocalizationResponseImageDataAttributesRelated';
import type { AboutLocalizationResponseLocalizations } from './AboutLocalizationResponseLocalizations';
import {
  AboutLocalizationResponseLocalizationsFromJSON,
  AboutLocalizationResponseLocalizationsFromJSONTyped,
  AboutLocalizationResponseLocalizationsToJSON,
} from './AboutLocalizationResponseLocalizations';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesArtists } from './ArtistLocalizationResponseArtworksDataInnerAttributesArtists';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesArtistsToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesArtists';
import type { ArtistLocalizationResponseArtworksDataInnerAttributesMedia } from './ArtistLocalizationResponseArtworksDataInnerAttributesMedia';
import {
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSON,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSONTyped,
  ArtistLocalizationResponseArtworksDataInnerAttributesMediaToJSON,
} from './ArtistLocalizationResponseArtworksDataInnerAttributesMedia';

/**
 *
 * @export
 * @interface IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
 */
export interface IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  description?: string;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesArtists}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  artists?: ArtistLocalizationResponseArtworksDataInnerAttributesArtists;
  /**
   *
   * @type {ArtistLocalizationResponseArtworksDataInnerAttributesMedia}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  media?: ArtistLocalizationResponseArtworksDataInnerAttributesMedia;
  /**
   *
   * @type {Date}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  creationDate?: Date;
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  originalTitle?: string;
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  handle?: string;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesRelated}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  exhibitions?: AboutLocalizationResponseImageDataAttributesRelated;
  /**
   *
   * @type {Date}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutLocalizationResponseLocalizations}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  localizations?: AboutLocalizationResponseLocalizations;
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes interface.
 */
export function instanceOfIndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributesFromJSON(
  json: any
): IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes {
  return IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    artists: !exists(json, 'artists')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesArtistsFromJSON(json['artists']),
    media: !exists(json, 'media')
      ? undefined
      : ArtistLocalizationResponseArtworksDataInnerAttributesMediaFromJSON(json['media']),
    creationDate: !exists(json, 'creationDate') ? undefined : new Date(json['creationDate']),
    originalTitle: !exists(json, 'originalTitle') ? undefined : json['originalTitle'],
    handle: !exists(json, 'handle') ? undefined : json['handle'],
    exhibitions: !exists(json, 'exhibitions')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesRelatedFromJSON(json['exhibitions']),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    publishedAt: !exists(json, 'publishedAt') ? undefined : new Date(json['publishedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
    localizations: !exists(json, 'localizations')
      ? undefined
      : AboutLocalizationResponseLocalizationsFromJSON(json['localizations']),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributesToJSON(
  value?: IndexLocalizationResponseExhibitionsDataInnerAttributesArtworksDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    description: value.description,
    artists: ArtistLocalizationResponseArtworksDataInnerAttributesArtistsToJSON(value.artists),
    media: ArtistLocalizationResponseArtworksDataInnerAttributesMediaToJSON(value.media),
    creationDate:
      value.creationDate === undefined ? undefined : value.creationDate.toISOString().substr(0, 10),
    originalTitle: value.originalTitle,
    handle: value.handle,
    exhibitions: AboutLocalizationResponseImageDataAttributesRelatedToJSON(value.exhibitions),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt: value.publishedAt === undefined ? undefined : value.publishedAt.toISOString(),
    createdBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.createdBy
    ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
    localizations: AboutLocalizationResponseLocalizationsToJSON(value.localizations),
    locale: value.locale,
  };
}
