/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ArtistLocalizationRequestArtworksInner } from './ArtistLocalizationRequestArtworksInner';
import {
  ArtistLocalizationRequestArtworksInnerFromJSON,
  ArtistLocalizationRequestArtworksInnerFromJSONTyped,
  ArtistLocalizationRequestArtworksInnerToJSON,
} from './ArtistLocalizationRequestArtworksInner';

/**
 *
 * @export
 * @interface IndexLocalizationRequest
 */
export interface IndexLocalizationRequest {
  /**
   *
   * @type {Array<ArtistLocalizationRequestArtworksInner>}
   * @memberof IndexLocalizationRequest
   */
  exhibitions?: Array<ArtistLocalizationRequestArtworksInner>;
  /**
   *
   * @type {ArtistLocalizationRequestArtworksInner}
   * @memberof IndexLocalizationRequest
   */
  update?: ArtistLocalizationRequestArtworksInner;
  /**
   *
   * @type {string}
   * @memberof IndexLocalizationRequest
   */
  locale: string;
}

/**
 * Check if a given object implements the IndexLocalizationRequest interface.
 */
export function instanceOfIndexLocalizationRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'locale' in value;

  return isInstance;
}

export function IndexLocalizationRequestFromJSON(json: any): IndexLocalizationRequest {
  return IndexLocalizationRequestFromJSONTyped(json, false);
}

export function IndexLocalizationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexLocalizationRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    exhibitions: !exists(json, 'exhibitions')
      ? undefined
      : (json['exhibitions'] as Array<any>).map(ArtistLocalizationRequestArtworksInnerFromJSON),
    update: !exists(json, 'update')
      ? undefined
      : ArtistLocalizationRequestArtworksInnerFromJSON(json['update']),
    locale: json['locale'],
  };
}

export function IndexLocalizationRequestToJSON(value?: IndexLocalizationRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    exhibitions:
      value.exhibitions === undefined
        ? undefined
        : (value.exhibitions as Array<any>).map(ArtistLocalizationRequestArtworksInnerToJSON),
    update: ArtistLocalizationRequestArtworksInnerToJSON(value.update),
    locale: value.locale,
  };
}
