/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexUpdateDataAttributes } from './IndexUpdateDataAttributes';
import {
  IndexUpdateDataAttributesFromJSON,
  IndexUpdateDataAttributesFromJSONTyped,
  IndexUpdateDataAttributesToJSON,
} from './IndexUpdateDataAttributes';

/**
 *
 * @export
 * @interface IndexUpdateData
 */
export interface IndexUpdateData {
  /**
   *
   * @type {number}
   * @memberof IndexUpdateData
   */
  id?: number;
  /**
   *
   * @type {IndexUpdateDataAttributes}
   * @memberof IndexUpdateData
   */
  attributes?: IndexUpdateDataAttributes;
}

/**
 * Check if a given object implements the IndexUpdateData interface.
 */
export function instanceOfIndexUpdateData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexUpdateDataFromJSON(json: any): IndexUpdateData {
  return IndexUpdateDataFromJSONTyped(json, false);
}

export function IndexUpdateDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexUpdateData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : IndexUpdateDataAttributesFromJSON(json['attributes']),
  };
}

export function IndexUpdateDataToJSON(value?: IndexUpdateData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: IndexUpdateDataAttributesToJSON(value.attributes),
  };
}
