/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexLocalizationResponseUpdateDataAttributes } from './IndexLocalizationResponseUpdateDataAttributes';
import {
  IndexLocalizationResponseUpdateDataAttributesFromJSON,
  IndexLocalizationResponseUpdateDataAttributesFromJSONTyped,
  IndexLocalizationResponseUpdateDataAttributesToJSON,
} from './IndexLocalizationResponseUpdateDataAttributes';

/**
 *
 * @export
 * @interface IndexLocalizationResponseUpdateData
 */
export interface IndexLocalizationResponseUpdateData {
  /**
   *
   * @type {number}
   * @memberof IndexLocalizationResponseUpdateData
   */
  id?: number;
  /**
   *
   * @type {IndexLocalizationResponseUpdateDataAttributes}
   * @memberof IndexLocalizationResponseUpdateData
   */
  attributes?: IndexLocalizationResponseUpdateDataAttributes;
}

/**
 * Check if a given object implements the IndexLocalizationResponseUpdateData interface.
 */
export function instanceOfIndexLocalizationResponseUpdateData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexLocalizationResponseUpdateDataFromJSON(
  json: any
): IndexLocalizationResponseUpdateData {
  return IndexLocalizationResponseUpdateDataFromJSONTyped(json, false);
}

export function IndexLocalizationResponseUpdateDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexLocalizationResponseUpdateData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : IndexLocalizationResponseUpdateDataAttributesFromJSON(json['attributes']),
  };
}

export function IndexLocalizationResponseUpdateDataToJSON(
  value?: IndexLocalizationResponseUpdateData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: IndexLocalizationResponseUpdateDataAttributesToJSON(value.attributes),
  };
}
