/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IndexListResponseDataItemLocalizedAttributes } from './IndexListResponseDataItemLocalizedAttributes';
import {
  IndexListResponseDataItemLocalizedAttributesFromJSON,
  IndexListResponseDataItemLocalizedAttributesFromJSONTyped,
  IndexListResponseDataItemLocalizedAttributesToJSON,
} from './IndexListResponseDataItemLocalizedAttributes';

/**
 *
 * @export
 * @interface IndexListResponseDataItemLocalized
 */
export interface IndexListResponseDataItemLocalized {
  /**
   *
   * @type {number}
   * @memberof IndexListResponseDataItemLocalized
   */
  id?: number;
  /**
   *
   * @type {IndexListResponseDataItemLocalizedAttributes}
   * @memberof IndexListResponseDataItemLocalized
   */
  attributes?: IndexListResponseDataItemLocalizedAttributes;
}

/**
 * Check if a given object implements the IndexListResponseDataItemLocalized interface.
 */
export function instanceOfIndexListResponseDataItemLocalized(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexListResponseDataItemLocalizedFromJSON(
  json: any
): IndexListResponseDataItemLocalized {
  return IndexListResponseDataItemLocalizedFromJSONTyped(json, false);
}

export function IndexListResponseDataItemLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexListResponseDataItemLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : IndexListResponseDataItemLocalizedAttributesFromJSON(json['attributes']),
  };
}

export function IndexListResponseDataItemLocalizedToJSON(
  value?: IndexListResponseDataItemLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: IndexListResponseDataItemLocalizedAttributesToJSON(value.attributes),
  };
}
