/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { IndexLocalizationResponseExhibitions } from './IndexLocalizationResponseExhibitions';
import {
  IndexLocalizationResponseExhibitionsFromJSON,
  IndexLocalizationResponseExhibitionsFromJSONTyped,
  IndexLocalizationResponseExhibitionsToJSON,
} from './IndexLocalizationResponseExhibitions';
import type { IndexLocalizationResponseUpdate } from './IndexLocalizationResponseUpdate';
import {
  IndexLocalizationResponseUpdateFromJSON,
  IndexLocalizationResponseUpdateFromJSONTyped,
  IndexLocalizationResponseUpdateToJSON,
} from './IndexLocalizationResponseUpdate';
import type { IndexResponseDataObjectAttributesLocalizations } from './IndexResponseDataObjectAttributesLocalizations';
import {
  IndexResponseDataObjectAttributesLocalizationsFromJSON,
  IndexResponseDataObjectAttributesLocalizationsFromJSONTyped,
  IndexResponseDataObjectAttributesLocalizationsToJSON,
} from './IndexResponseDataObjectAttributesLocalizations';

/**
 *
 * @export
 * @interface IndexResponseDataObjectAttributes
 */
export interface IndexResponseDataObjectAttributes {
  /**
   *
   * @type {IndexLocalizationResponseExhibitions}
   * @memberof IndexResponseDataObjectAttributes
   */
  exhibitions?: IndexLocalizationResponseExhibitions;
  /**
   *
   * @type {IndexLocalizationResponseUpdate}
   * @memberof IndexResponseDataObjectAttributes
   */
  update?: IndexLocalizationResponseUpdate;
  /**
   *
   * @type {Date}
   * @memberof IndexResponseDataObjectAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexResponseDataObjectAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexResponseDataObjectAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexResponseDataObjectAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {IndexResponseDataObjectAttributesLocalizations}
   * @memberof IndexResponseDataObjectAttributes
   */
  localizations?: IndexResponseDataObjectAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof IndexResponseDataObjectAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the IndexResponseDataObjectAttributes interface.
 */
export function instanceOfIndexResponseDataObjectAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexResponseDataObjectAttributesFromJSON(
  json: any
): IndexResponseDataObjectAttributes {
  return IndexResponseDataObjectAttributesFromJSONTyped(json, false);
}

export function IndexResponseDataObjectAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexResponseDataObjectAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    exhibitions: !exists(json, 'exhibitions')
      ? undefined
      : IndexLocalizationResponseExhibitionsFromJSON(json['exhibitions']),
    update: !exists(json, 'update')
      ? undefined
      : IndexLocalizationResponseUpdateFromJSON(json['update']),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
    localizations: !exists(json, 'localizations')
      ? undefined
      : IndexResponseDataObjectAttributesLocalizationsFromJSON(json['localizations']),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function IndexResponseDataObjectAttributesToJSON(
  value?: IndexResponseDataObjectAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    exhibitions: IndexLocalizationResponseExhibitionsToJSON(value.exhibitions),
    update: IndexLocalizationResponseUpdateToJSON(value.update),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.createdBy
    ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
    localizations: IndexResponseDataObjectAttributesLocalizationsToJSON(value.localizations),
    locale: value.locale,
  };
}
