/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutImageDataAttributesFolderDataAttributesParent } from './AboutImageDataAttributesFolderDataAttributesParent';
import {
  AboutImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutImageDataAttributesFolderDataAttributesParent';
import type { ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations } from './ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations';
import {
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSON,
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSONTyped,
  ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsToJSON,
} from './ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations';
import type { ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover } from './ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover';
import {
  ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSON,
  ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSONTyped,
  ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverToJSON,
} from './ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover';
import type { IndexExhibitionsDataInnerAttributesArtworks } from './IndexExhibitionsDataInnerAttributesArtworks';
import {
  IndexExhibitionsDataInnerAttributesArtworksFromJSON,
  IndexExhibitionsDataInnerAttributesArtworksFromJSONTyped,
  IndexExhibitionsDataInnerAttributesArtworksToJSON,
} from './IndexExhibitionsDataInnerAttributesArtworks';

/**
 *
 * @export
 * @interface IndexExhibitionsDataInnerAttributes
 */
export interface IndexExhibitionsDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  handle?: string;
  /**
   *
   * @type {IndexExhibitionsDataInnerAttributesArtworks}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  artworks?: IndexExhibitionsDataInnerAttributesArtworks;
  /**
   *
   * @type {ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  cover?: ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCover;
  /**
   *
   * @type {Date}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  launch?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {AboutImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  createdBy?: AboutImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {AboutImageDataAttributesFolderDataAttributesParent}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  updatedBy?: AboutImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  localizations?: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof IndexExhibitionsDataInnerAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the IndexExhibitionsDataInnerAttributes interface.
 */
export function instanceOfIndexExhibitionsDataInnerAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function IndexExhibitionsDataInnerAttributesFromJSON(
  json: any
): IndexExhibitionsDataInnerAttributes {
  return IndexExhibitionsDataInnerAttributesFromJSONTyped(json, false);
}

export function IndexExhibitionsDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IndexExhibitionsDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    handle: !exists(json, 'handle') ? undefined : json['handle'],
    artworks: !exists(json, 'artworks')
      ? undefined
      : IndexExhibitionsDataInnerAttributesArtworksFromJSON(json['artworks']),
    cover: !exists(json, 'cover')
      ? undefined
      : ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverFromJSON(json['cover']),
    launch: !exists(json, 'launch') ? undefined : new Date(json['launch']),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    publishedAt: !exists(json, 'publishedAt') ? undefined : new Date(json['publishedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutImageDataAttributesFolderDataAttributesParentFromJSON(json['createdBy']),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutImageDataAttributesFolderDataAttributesParentFromJSON(json['updatedBy']),
    localizations: !exists(json, 'localizations')
      ? undefined
      : ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsFromJSON(
          json['localizations']
        ),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function IndexExhibitionsDataInnerAttributesToJSON(
  value?: IndexExhibitionsDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    description: value.description,
    handle: value.handle,
    artworks: IndexExhibitionsDataInnerAttributesArtworksToJSON(value.artworks),
    cover: ArtistArtworksDataInnerAttributesExhibitionsDataInnerAttributesCoverToJSON(value.cover),
    launch: value.launch === undefined ? undefined : value.launch.toISOString(),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt: value.publishedAt === undefined ? undefined : value.publishedAt.toISOString(),
    createdBy: AboutImageDataAttributesFolderDataAttributesParentToJSON(value.createdBy),
    updatedBy: AboutImageDataAttributesFolderDataAttributesParentToJSON(value.updatedBy),
    localizations: ArtistArtworksDataInnerAttributesArtistsDataInnerAttributesLocalizationsToJSON(
      value.localizations
    ),
    locale: value.locale,
  };
}
