/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateListResponseDataItemLocalizedAttributes } from './UpdateListResponseDataItemLocalizedAttributes';
import {
  UpdateListResponseDataItemLocalizedAttributesFromJSON,
  UpdateListResponseDataItemLocalizedAttributesFromJSONTyped,
  UpdateListResponseDataItemLocalizedAttributesToJSON,
} from './UpdateListResponseDataItemLocalizedAttributes';

/**
 *
 * @export
 * @interface UpdateListResponseDataItemLocalized
 */
export interface UpdateListResponseDataItemLocalized {
  /**
   *
   * @type {number}
   * @memberof UpdateListResponseDataItemLocalized
   */
  id?: number;
  /**
   *
   * @type {UpdateListResponseDataItemLocalizedAttributes}
   * @memberof UpdateListResponseDataItemLocalized
   */
  attributes?: UpdateListResponseDataItemLocalizedAttributes;
}

/**
 * Check if a given object implements the UpdateListResponseDataItemLocalized interface.
 */
export function instanceOfUpdateListResponseDataItemLocalized(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateListResponseDataItemLocalizedFromJSON(
  json: any
): UpdateListResponseDataItemLocalized {
  return UpdateListResponseDataItemLocalizedFromJSONTyped(json, false);
}

export function UpdateListResponseDataItemLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateListResponseDataItemLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    attributes: !exists(json, 'attributes')
      ? undefined
      : UpdateListResponseDataItemLocalizedAttributesFromJSON(json['attributes']),
  };
}

export function UpdateListResponseDataItemLocalizedToJSON(
  value?: UpdateListResponseDataItemLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: UpdateListResponseDataItemLocalizedAttributesToJSON(value.attributes),
  };
}
