/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy';
import type { AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent } from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import {
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSONTyped,
  AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON,
} from './AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent';
import type { UpdateListResponseDataItemAttributesLocalizations } from './UpdateListResponseDataItemAttributesLocalizations';
import {
  UpdateListResponseDataItemAttributesLocalizationsFromJSON,
  UpdateListResponseDataItemAttributesLocalizationsFromJSONTyped,
  UpdateListResponseDataItemAttributesLocalizationsToJSON,
} from './UpdateListResponseDataItemAttributesLocalizations';

/**
 *
 * @export
 * @interface UpdateListResponseDataItemAttributes
 */
export interface UpdateListResponseDataItemAttributes {
  /**
   *
   * @type {string}
   * @memberof UpdateListResponseDataItemAttributes
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateListResponseDataItemAttributes
   */
  content?: string;
  /**
   *
   * @type {Date}
   * @memberof UpdateListResponseDataItemAttributes
   */
  datetime?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateListResponseDataItemAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateListResponseDataItemAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateListResponseDataItemAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy}
   * @memberof UpdateListResponseDataItemAttributes
   */
  createdBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
  /**
   *
   * @type {AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent}
   * @memberof UpdateListResponseDataItemAttributes
   */
  updatedBy?: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParent;
  /**
   *
   * @type {UpdateListResponseDataItemAttributesLocalizations}
   * @memberof UpdateListResponseDataItemAttributes
   */
  localizations?: UpdateListResponseDataItemAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof UpdateListResponseDataItemAttributes
   */
  locale?: string;
}

/**
 * Check if a given object implements the UpdateListResponseDataItemAttributes interface.
 */
export function instanceOfUpdateListResponseDataItemAttributes(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateListResponseDataItemAttributesFromJSON(
  json: any
): UpdateListResponseDataItemAttributes {
  return UpdateListResponseDataItemAttributesFromJSONTyped(json, false);
}

export function UpdateListResponseDataItemAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateListResponseDataItemAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    content: !exists(json, 'content') ? undefined : json['content'],
    datetime: !exists(json, 'datetime') ? undefined : new Date(json['datetime']),
    createdAt: !exists(json, 'createdAt') ? undefined : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt') ? undefined : new Date(json['updatedAt']),
    publishedAt: !exists(json, 'publishedAt') ? undefined : new Date(json['publishedAt']),
    createdBy: !exists(json, 'createdBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
          json['createdBy']
        ),
    updatedBy: !exists(json, 'updatedBy')
      ? undefined
      : AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentFromJSON(
          json['updatedBy']
        ),
    localizations: !exists(json, 'localizations')
      ? undefined
      : UpdateListResponseDataItemAttributesLocalizationsFromJSON(json['localizations']),
    locale: !exists(json, 'locale') ? undefined : json['locale'],
  };
}

export function UpdateListResponseDataItemAttributesToJSON(
  value?: UpdateListResponseDataItemAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    content: value.content,
    datetime: value.datetime === undefined ? undefined : value.datetime.toISOString(),
    createdAt: value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt: value.publishedAt === undefined ? undefined : value.publishedAt.toISOString(),
    createdBy:
      AboutLocalizationResponseImageDataAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
        value.createdBy
      ),
    updatedBy: AboutLocalizationResponseImageDataAttributesFolderDataAttributesParentToJSON(
      value.updatedBy
    ),
    localizations: UpdateListResponseDataItemAttributesLocalizationsToJSON(value.localizations),
    locale: value.locale,
  };
}
