/* tslint:disable */
/* eslint-disable */
/**
 * zwischenwelten API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@jeschek.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateListResponseDataItemLocalized } from './UpdateListResponseDataItemLocalized';
import {
  UpdateListResponseDataItemLocalizedFromJSON,
  UpdateListResponseDataItemLocalizedFromJSONTyped,
  UpdateListResponseDataItemLocalizedToJSON,
} from './UpdateListResponseDataItemLocalized';

/**
 *
 * @export
 * @interface UpdateListResponseDataItemAttributesLocalizations
 */
export interface UpdateListResponseDataItemAttributesLocalizations {
  /**
   *
   * @type {Array<UpdateListResponseDataItemLocalized>}
   * @memberof UpdateListResponseDataItemAttributesLocalizations
   */
  data?: Array<UpdateListResponseDataItemLocalized>;
}

/**
 * Check if a given object implements the UpdateListResponseDataItemAttributesLocalizations interface.
 */
export function instanceOfUpdateListResponseDataItemAttributesLocalizations(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateListResponseDataItemAttributesLocalizationsFromJSON(
  json: any
): UpdateListResponseDataItemAttributesLocalizations {
  return UpdateListResponseDataItemAttributesLocalizationsFromJSONTyped(json, false);
}

export function UpdateListResponseDataItemAttributesLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateListResponseDataItemAttributesLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, 'data')
      ? undefined
      : (json['data'] as Array<any>).map(UpdateListResponseDataItemLocalizedFromJSON),
  };
}

export function UpdateListResponseDataItemAttributesLocalizationsToJSON(
  value?: UpdateListResponseDataItemAttributesLocalizations | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(UpdateListResponseDataItemLocalizedToJSON),
  };
}
